import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Header from './components/header/Header'

const roboto = Roboto({
    weight: '400',
    subsets: ['vietnamese'],
    variable: '--font-roboto',
})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className={roboto.variable}>
            <body className='bg-background text-foreground'>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    )
}
